#! /bin/bash

# Reboot if Chromium is not running

# Save this file to '/home/pi/scripts/reboot_on_chromium_fail' for the crontab to work

status=$(ps aux | grep "chromium" | grep "\-\-app" | grep -v "grep")

if [[ -z "$status" ]]; then
  # Chromium is not running
  sudo shutdown -r now
  exit 0
fi
