#!/bin/bash

/usr/bin/chromium --kiosk --touch-events=enabled --disable-pinch --noerrdialogs -disable-session-crashed-bubble --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' --disable-component-update --overscroll-history-navigation=0 --disable-features=TranslateUI --app=$(cat /boot/link.txt)
exit;
